version: '3.7'
services:
  frontend:
    image: szabacsik/ubuntu_nginx_php-fpm_phalcon:latest
    container_name: frontend
    hostname: frontend
    environment:
      - HOSTNAME=frontend
    ports:
      - 80:80
      - 9001:9001
    networks:
      - backendNetwork
    volumes:
      - /home/worker/volumes/frontend:/home/worker/volume
      - type: bind
        source: ./nginx-frontend.conf
        target: /etc/nginx/sites-available/nginx.conf
    restart: "no"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    hostname: mongodb
    ports:
      - 27017:27017
    networks:
      - backendNetwork
    volumes:
      - /home/worker/volumes/mongodb:/data
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /data/log
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: PASSWORD
      MONGO_INITDB_DATABASE: mongofony
    restart: "always"
  mongo-express:
    image: mongo-express:latest
    restart: always
    ports:
      - 8081:8081
    networks:
      - backendNetwork
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: PASSWORD
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: PASSWORD
      ME_CONFIG_OPTIONS_EDITORTHEME: darcula
    depends_on:
      - mongodb
networks:
  backendNetwork:
    name: backend_network